# Generated by Django 5.2.3 on 2025-08-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="followers",
            new_name="followering",
        ),
    ]
