# Generated by Django 5.2.3 on 2025-08-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_followers_user_followering"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="followering",
            new_name="following",
        ),
    ]
