# Generated by Django 5.2.3 on 2025-08-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
