# Generated by Django 5.2.3 on 2025-08-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="liked_by",
            new_name="user",
        ),
    ]
